name: Validate Dependabot Updates

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    strategy:
      matrix:
        node-version: [24.2.0]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Security audit
        run: pnpm audit --audit-level=moderate || true

      - name: Format write
        run: pnpm format:write

      - name: Type check
        run: pnpm tsc

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test --coverage

      - name: Build
        run: pnpm build

  auto-merge:
    needs: validate
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && success() }}
    permissions:
      pull-requests: write
    
    steps:
      - name: Auto-merge approved PRs
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const prTitle = pr.title;
            
            // Major updates require manual review
            if (prTitle.includes('deps:') && !prTitle.includes('deps(dev)')) {
              console.log('Major dependency update - requires manual review');
              return;
            }
            
            // Auto-approve and merge
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              event: 'APPROVE',
              body: '✅ All tests passed! Auto-approving dependency update.'
            });
            
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              merge_method: 'squash',
              commit_title: prTitle,
              commit_message: 'Automatically merged after successful tests'
            });
